name: Publish

on:
  push:
    tags: [ "v*" ]
  release:
    types: [ created ]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Extract version
        id: tag
        uses: actions/github-script@v6.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.ref.replace('refs/tags/v', '');
      - uses: actions/setup-node@v3
        with:
          node-version: 17
          registry-url: https://npm.pkg.github.com/
          always-auth: true
      - run: npm ci
      - run: npm version --no-git-tag-version --no-commit-hooks ${{ steps.tag.outputs.result }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
